# site settings
title: BIRDS Bus Open Source | Docs
tagline: An Open Source Bus System for Academic Satellites
description: The BIRDSOpenSource release is a comprehensive open source guide for designing, building, testing, and launching a small satellite. Whether you’re a beginner or an experienced developer, our resources are structured to assist you at every stage of the satellite development process.
email: birds_opensource@lean-sat.org
telegram: https://t.me/+D3BCqCmceQ41ZGFl
mailing_list: https://lean-sat.org/opensource/
youtube: https://www.youtube.com/@kyutechseic4187
github_org: https://github.com/BIRDSOpenSource

# theme
theme: just-the-docs

# urls
repository: BIRDSOpenSource/BIRDSOpenSource.github.io/ # for github-metadata
baseurl: "" # the subpath of your site, e.g. /blog
url: https://birdsopensource.github.io
logo: "/assets/images/birds-logo-light.png" # Set a path/url to a logo that will be displayed instead of the title
favicon_ico: "/assets/images/favicon.ico" # Set a path/url to a favicon that will be displayed by the browser

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

# For copy button on code
enable_copy_code_button: true

# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.4.0"
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code
  # To load mermaid from a local library, also use the `path` key to specify the location of the library; e.g.
  # for (v10+):
  path: "/assets/js/mermaid.esm.min.mjs"
  # for (<v10):
  # path: "/assets/js/mermaid.min.js"
  # Note: copy both `mermaid.esm.min.mjs` (v10+) or `mermaid.min.js` (<v10) and the associated `.map` file from the specified version of `mermaid/dist` to `/assets/js/`.

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "BIRDSOpenSource on GitHub":
    - "{{site.github_org}}"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Color scheme supports "light" (default) and "dark"
color_schemes:
  - light
  - dark
  
color_scheme: dark

# # Define Jekyll collections
# collections:
#   resources:
#     permalink: "/:collection/:path/"
#     output: true

# just_the_docs:
#   # Define which collections are used in just-the-docs
#   collections:
#     resources:
#       name: Resources

callouts_opacity: 0.3
callouts:
  warning:
    title: Warning
    color: red
    opacity: 0.3
  
  caution:
    title: Caution
    color: yellow
    opacity: 0.5

  note:
    title: Note
    color: blue
    opacity: 0.7

# l10n
# languages: ["en", "jp"]
# default_lang: "en"
# exclude_from_localization: ["assets/diagrams", "assets/images"]
# parallel_localization: true
# language_labels:
#   en: English
#   jp: 日本語
# sass:
#   sourcemap: never

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap
