theme: jekyll-theme-minimal
title: Birds Open Source Release
description: Kyushu Institute of Technology
logo: ./assets/images/logo_2018_07.png
show_downloads: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag