name            : Birds Open Source
description     : Helping low-budget teams in non-space faring nations by providing a more solid basis for satellite development.
logo            : '/images/logo_2018_07.png'
url             : https://birdsopensource.github.io/
show_downloads  : false
theme           : jekyll-theme-glueckkanja
# plugins         :
# - jekyll-seo-tag
# - jekyll-sitemap

defaults        :
 - 
  scope         :
    path        : pages
  values        :
      layout    : page